# 안녕하세요^^ 
# AIVLE 미니 프로젝트에 오신 여러분을 환영합니다.
* 본 과정에서는 실제 사례와 데이터를 기반으로 문제를 해결하는 전체 과정을 자기 주도형 실습으로 진행해볼 예정입니다.
* 앞선 교육과정을 정리하는 마음과 지금까지 배운 내용을 바탕으로 문제 해결을 해볼게요!
* 미니 프로젝트를 통한 문제 해결 과정 'A에서 Z까지', 지금부터 시작합니다!

---

# (실습준비) 데이터 불러오기부터

* 17년도부터 21년도 까지의 데이터를 train set, 22년도의 6개월치 데이터를 test set 으로 설정합니다.

In [1]:
# 코랩 사용 시 구글 드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

MessageError: ignored

In [163]:
import pandas as pd

# 학습 데이터 로딩
df_total = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/미니프로젝트5차_생활인구 4_5일차/df_total.csv',sep = ',', index_col = 0)
df_test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/미니프로젝트5차_생활인구 4_5일차/df_test.csv', sep=',')

In [164]:
df_total.head()

,기준일ID,시간대구분,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
index,,,,,,,,,,,,,,,,,,,,,
0,2017-01-01,0,31535.2200,1945.4402,566.4588,631.5581,991.9184,1297.1287,1223.1529,1552.9448,...,1157.6661,1107.6781,1282.9235,1029.4360,998.0414,874.5643,1162.1547,1053.0477,964.3940,2025.4819
1,2017-01-01,1,31188.9174,1930.4766,562.1018,625.2151,1030.6281,1307.7381,1183.0956,1491.5827,...,1120.0051,1102.5198,1271.8997,1027.2574,1038.7528,857.9100,1149.7532,1042.7411,919.0115,2062.2422
2,2017-01-01,2,31240.4974,1921.1864,559.3965,658.7463,1058.7082,1311.9591,1186.2600,1537.3732,...,1103.1547,1112.4579,1282.9366,1027.8901,1020.0177,853.3890,1193.4472,1011.2073,889.9325,1960.1236
3,2017-01-01,3,31442.4314,1946.4476,566.7525,649.0804,1057.9119,1324.2638,1202.1250,1521.2732,...,1116.2165,1102.0668,1260.8472,1007.6650,1042.9554,896.0038,1163.0355,1056.6428,891.9177,2060.1872
4,2017-01-01,4,31922.7751,1953.7713,568.8845,623.2087,1063.2557,1342.9146,1209.2680,1556.0675,...,1187.5457,1120.2232,1281.2738,1064.0655,1045.2130,895.8336,1191.7017,1045.3362,874.4984,2038.6212

In [29]:
df_test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/미니프로젝트5차_생활인구 4_5일차/df_test.csv', sep=',')

---

# 1. 데이터 전처리

#### [실습문제1] 열 추가 
* 기존 '기준일ID'열에서 날짜 데이터를 추출하여 새로운 열로 추가 합니다.
    - pd.to_datetime() 함수를 사용해 '기준일ID'열을 datetime 형식으로 변경하겠습니다.
    - year, month, day 열로 기존 데이터 프레임에 연월일 정보를 저장합니다.
    - 데이터 프레임 열에 대해 날짜 정보를 얻을 때에는 **dt.year**, **dt.month**, **dt.day** 속성을 사용합니다.

In [77]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
df_total.tail()

,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,남자35세부터39세생활인구수,남자40세부터44세생활인구수,남자45세부터49세생활인구수,...,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수,year,hour
index,,,,,,,,,,,,,,,,,,,,,
43507,33060.4555,1858.2611,541.0746,605.9080,781.6602,1342.6763,1435.1080,1678.8904,1605.1525,1598.5467,...,1521.8562,1277.9546,1279.9036,977.2774,1091.7204,942.1525,789.2094,1705.8216,2021,19
43508,32360.1898,2093.8808,609.6807,612.5326,768.8351,1323.7124,1479.1382,1654.5005,1533.4662,1476.7221,...,1461.8649,1294.2541,1232.4805,918.4935,1062.8069,894.8617,792.1748,1726.3071,2021,20
43509,31417.3991,1983.6728,577.5909,639.2174,779.6693,1187.6783,1375.6785,1600.9946,1423.7113,1434.7766,...,1407.1924,1223.4195,1205.9346,908.4537,999.7321,874.9000,770.3955,1674.6047,2021,21
43510,30763.0563,2028.3314,590.5941,654.0295,790.1638,1133.6311,1362.0266,1548.7366,1456.9716,1440.2235,...,1391.1649,1213.3359,1110.3310,863.0019,991.0451,848.4622,753.9750,1727.0258,2021,22
43511,30404.2740,1903.8825,554.3582,615.0753,772.8499,1136.6157,1295.0434,1549.1984,1508.8052,1483.0320,...,1428.1257,1239.5283,1186.8895,805.3827,986.6660,872.1547,734.2503,1759.0664,2021,23

In [165]:

df_total['기준일ID'] = pd.to_datetime(df_total['기준일ID'])

df_test['기준일ID'] = pd.to_datetime(df_test['기준일ID'])

In [166]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
df_total['year'] = df_total['기준일ID'].dt.year
df_test['year'] = df_test['기준일ID'].dt.year

df_total['month'] = df_total['기준일ID'].dt.month
df_test['month'] = df_test['기준일ID'].dt.month

df_total['day'] = df_total['기준일ID'].dt.day
df_test['day'] = df_test['기준일ID'].dt.day

#### [실습문제2] 불필요한 열 제거 및 열 이름 변경
* df_total과 df_test에서 '총생활인구수'외에 불필요한 열을 제거 하도록 하겠습니다.
* 시간 데이터를 남기고, '시간대구분' column 을 'hour'로 rename 하도록 하겠습니다.

In [167]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
df_total['hour'] = df_total['시간대구분']
df_total.drop('시간대구분',axis = 1, inplace = True)
df_test['hour'] = df_test['시간대구분']
df_test.drop('시간대구분',axis = 1, inplace = True)
df_total.drop('기준일ID',axis = 1, inplace = True)
df_test.drop('기준일ID',axis = 1, inplace = True)

In [168]:
df_total = df_total[['총생활인구수','year','month','day','hour']]
df_test = df_test[['총생활인구수','year','month','day','hour']]

In [169]:
df_test.tail()

          총생활인구수  year  month  day  hour
4339  32969.6040  2022      6   30    19
4340  31014.6597  2022      6   30    20
4341  30923.2923  2022      6   30    21
4342  30509.5463  2022      6   30    22
4343  31184.8763  2022      6   30    23

In [87]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
df_total = df_total[['총생활인구수','year','month','day','hour']]

In [174]:
df_total.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43512 entries, 0 to 43511
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   총생활인구수           43512 non-null  float64
 1   year             43512 non-null  int64
 2   month            43512 non-null  int64
 3   day              43512 non-null  int64
 4   hour             43512 non-null  int64
 5   총생활인구수_lag_1416  42096 non-null  float64
dtypes: float64(2), int64(4)
memory usage: 2.3 MB

In [161]:
import numpy as np
df_total.tail()

           총생활인구수  year  month  day  hour  총생활인구수_lag_1416
index
43507  33060.4555  2021     12   31    19       34554.6229
43508  32360.1898  2021     12   31    20       33506.8350
43509  31417.3991  2021     12   31    21       32323.8287
43510  30763.0563  2021     12   31    22       31769.3180
43511  30404.2740  2021     12   31    23       32503.2263

#### [실습문제3] 시프트 & 롤링
* shift()를 활용하여 이동할 행 수를 지정합니다.
* rolling()을 활용하여 추가할 이동평균 수를 지정합니다.

In [171]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
# df_total['총생활인구수_lag_1416'] = df_total['총생활인구수'].shift(1416)
# df_total['총생활인구수_lag_7'] = df_total['총생활인구수'].shift(7)

In [ ]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.

#### [실습문제4] 결측치 처리 및 불필요한 열 제거
* 롤링 & 시프트 과정에서 발생한 결측치를 처리하도록 하겠습니다.
* 불필요한 열을 추가로 제거 하겠습니다.(시간 관련 행들)

In [175]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
df_total = df_total.dropna()
# df_total.drop(['level_0'],axis = 1, inplace = True)
df_total

           총생활인구수  year  month  day  hour  총생활인구수_lag_1416
index
1416   31209.1023  2017      3    1     0       31535.2200
1417   30334.7708  2017      3    1     1       31188.9174
1418   30558.3055  2017      3    1     2       31240.4974
1419   30789.1289  2017      3    1     3       31442.4314
1420   31420.6076  2017      3    1     4       31922.7751
...           ...   ...    ...  ...   ...              ...
43507  33060.4555  2021     12   31    19       34554.6229
43508  32360.1898  2021     12   31    20       33506.8350
43509  31417.3991  2021     12   31    21       32323.8287
43510  30763.0563  2021     12   31    22       31769.3180
43511  30404.2740  2021     12   31    23       32503.2263

[42096 rows x 6 columns]

In [ ]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.

#### [실습문제5] train, test 데이터 나누기
* df_total과 df_test를 각각 train_x, train_y, test_x, test_y 로 나누어 주세요.
* 인덱스를 리셋 해주세요.

In [132]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.
from sklearn.model_selection import train_test_split
x = df_total.drop('총생활인구수', axis = 1)
y = df_total.loc[:, '총생활인구수']

train_x, test_x, train_y, test_y = train_test_split(x,y, test_size = 0.2, shuffle = False)

In [135]:
# 아래에 실습코드를 작성하고 결과를 확인합니다.

       year  month  day  hour  총생활인구수_lag_1  총생활인구수_lag_7
34804  2021      1    3    11    33284.1112    31722.0167
34805  2021      1    3    12    32879.9602    31942.3392
34806  2021      1    3    13    33506.0451    32110.8386
34807  2021      1    3    14    33269.5357    32682.0765
34808  2021      1    3    15    33571.7711    33040.4011
...     ...    ...  ...   ...           ...           ...
43500  2021     12   31    19    35883.1874    38306.0838
43501  2021     12   31    20    33060.4555    39452.9085
43502  2021     12   31    21    32360.1898    38546.9114
43503  2021     12   31    22    31417.3991    37018.4693
43504  2021     12   31    23    30763.0563    36488.7566

[8701 rows x 6 columns]

---

## 다음 단계를 위해서 데이터를 저장하겠습니다.

In [136]:
# CSV로 저장
train_x.to_csv('/content/drive/MyDrive/Colab Notebooks/미니프로젝트5차_생활인구 4_5일차/train_x.csv', index = False)
train_y.to_csv('/content/drive/MyDrive/Colab Notebooks/미니프로젝트5차_생활인구 4_5일차/train_y.csv', index = False)
test_x.to_csv('/content/drive/MyDrive/Colab Notebooks/미니프로젝트5차_생활인구 4_5일차/test_x.csv', index = False)
test_y.to_csv('/content/drive/MyDrive/Colab Notebooks/미니프로젝트5차_생활인구 4_5일차/test_y.csv', index = False)

In [176]:
df_total_1 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/미니프로젝트5차_생활인구 4_5일차/df_total.csv',sep = ',', index_col = 0)
df_test_1 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/미니프로젝트5차_생활인구 4_5일차/df_test.csv', sep=',')

In [179]:
df_total_1['기준일ID'] = pd.to_datetime(df_total_1['기준일ID'])
df_test_1['기준일ID'] = pd.to_datetime(df_test_1['기준일ID'])

In [180]:
df_total_1['year'] = df_total_1['기준일ID'].dt.year
df_test_1['year'] = df_test_1['기준일ID'].dt.year

df_total_1['month'] = df_total_1['기준일ID'].dt.month
df_test_1['month'] = df_test_1['기준일ID'].dt.month

df_total_1['day'] = df_total_1['기준일ID'].dt.day
df_test_1['day'] = df_test_1['기준일ID'].dt.day

In [182]:
df_total_1['hour'] = df_total_1['시간대구분']
df_total_1.drop('시간대구분',axis = 1, inplace = True)
df_test_1['hour'] = df_test_1['시간대구분']
df_test_1.drop('시간대구분',axis = 1, inplace = True)
df_total_1.drop('기준일ID',axis = 1, inplace = True)
df_test_1.drop('기준일ID',axis = 1, inplace = True)

In [183]:
df_total_1 = df_total_1[['총생활인구수','year','month','day','hour']]
df_test_1 = df_test_1[['총생활인구수','year','month','day','hour']]

In [196]:
df_total_1 = df_total_1.loc[(df_total_1['month'] == 1) | (df_total_1['month'] == 2),]
df_test_1 = df_test_1.loc[(df_test_1['month'] == 1) | (df_test_1['month'] == 2),]

In [225]:
# df_test_1.loc[(df_total_1['day']==31) & (df_total_1['month'] == 1), ]

In [226]:
# df_test_1.loc[(df_test_1['day']==31) & (df_test_1['month'] == 1), ]

In [199]:
target = '총생활인구수'
a = df_total_1.drop(target, axis = 1)

In [227]:
test_y.shape

(1416,)

In [215]:
a = a.sample()

(7104, 4)

In [231]:
test_x = test_x.sort_values('index')

In [228]:
train_x = df_total_1.drop(target, axis = 1)
train_y = df_total_1.loc[:, target]
test_x = a.sample(n=1416)
test_y = df_test_1.loc[:, target]

In [235]:
test_x.shape

(1416, 4)

In [210]:
test_x.shape

(1421, 4)

In [236]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from numpy import square
from sklearn.model_selection import TimeSeriesSplit
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from xgboost import XGBRFRegressor
import numpy as np
from sklearn.linear_model import LinearRegression

In [238]:
model = RandomForestRegressor()
model.fit(train_x, train_y)
pred = model.predict(test_x)

In [234]:
print('RMSE :', mean_squared_error(test_y, pred, squared = False))
print('r2_score :', r2_score(test_y, pred))

RMSE : 5409.974684058263
r2_score : -3.096446647963928

In [239]:
model2 = XGBRegressor()
model2.fit(train_x, train_y)
pred2 = model2.predict(test_x)

[07:52:07] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

In [240]:
print('RMSE :', mean_squared_error(test_y, pred2, squared = False))
print('r2_score :', r2_score(test_y, pred2))

RMSE : 5200.02203255563
r2_score : -2.7846629164045265

In [241]:
model3 = XGBRFRegressor()
model3.fit(train_x, train_y)
pred3 = model3.predict(test_x)

[07:52:43] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

In [242]:
print('RMSE :', mean_squared_error(test_y, pred3, squared = False))
print('r2_score :', r2_score(test_y, pred3))

RMSE : 4633.7243645482
r2_score : -2.005226640339403

In [243]:
model4 = LinearRegression()
model4.fit(train_x, train_y)
pred4= model4.predict(test_x)

In [244]:
print('RMSE :', mean_squared_error(test_y, pred4, squared = False))
print('r2_score :', r2_score(test_y, pred4))

RMSE : 3946.970862782804
r2_score : -1.180442698794439

In [246]:
from sklearn.preprocessing import MinMaxScaler

In [247]:
scaler = MinMaxScaler()
# 함수 만들고
train_x_s = scaler.fit_transform(train_x)
test_x_s = scaler.fit_transform(test_x)

# # 변환시키기
# train_x = scaler.transform(train_x)
# test_x = scaler.transform(test_x)

In [248]:
from sklearn.svm import SVC, SVR

In [251]:
model5 = SVR()
model5.fit(train_x_s, train_y)
pred5 = model5.predict(test_x_s)

In [252]:
print('RMSE :', mean_squared_error(test_y, pred5, squared = False))
print('r2_score :', r2_score(test_y, pred5))

RMSE : 3399.4649092582667
r2_score : -0.6174764360665592

In [259]:
from sklearn.linear_model import Ridge

model6 = Ridge(alpha=1,
                 solver="cholesky",
                 random_state=42)
model6.fit(train_x_s,train_y)
pred6 = model6.predict(test_x_s)   # 새로운 샘플에 대한 예측

In [260]:
print('RMSE :', mean_squared_error(test_y, pred6, squared = False))
print('r2_score :', r2_score(test_y, pred6))

RMSE : 3946.207952215143
r2_score : -1.1795998640903065

In [263]:
from sklearn.linear_model import SGDRegressor
model7 = SGDRegressor()
model7.fit(train_x_s, train_y)
pred7 = model7.predict(test_x_s)

In [264]:
print('RMSE :', mean_squared_error(test_y, pred7, squared = False))
print('r2_score :', r2_score(test_y, pred7))

RMSE : 3992.1093090657655
r2_score : -1.2305999388484299

In [266]:
from sklearn.linear_model import Lasso
model8 = Lasso()
model8.fit(train_x_s, train_y)
pred8 = model8.predict(test_x_s)

In [267]:
print('RMSE :', mean_squared_error(test_y, pred8, squared = False))
print('r2_score :', r2_score(test_y, pred8))

RMSE : 3945.381890592687
r2_score : -1.1786874462077406

---